spring:
  application:
    name: high-traffic
  datasource:
    url: jdbc:mysql://localhost:3306/traffic-db
    username: traffic-user
    password: traffic1!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
